import { VideoReel, Product } from '@/types';

const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Premium Leather Bag',
    nameAr: 'حقيبة جلدية فاخرة',
    price: 299.99,
    currency: 'SAR',
    sellerId: 'seller1',
    sellerName: 'متجر الأناقة',
    images: [],
    category: 'fashion',
    stock: 15,
  },
  {
    id: '2',
    name: 'Wireless Headphones',
    nameAr: 'سماعات لاسلكية',
    price: 449.99,
    currency: 'SAR',
    sellerId: 'seller2',
    sellerName: 'تك ستور',
    images: [],
    category: 'electronics',
    stock: 30,
  },
  {
    id: '3',
    name: 'Smart Watch Pro',
    nameAr: 'ساعة ذكية برو',
    price: 899.99,
    currency: 'SAR',
    sellerId: 'seller2',
    sellerName: 'تك ستور',
    images: [],
    category: 'electronics',
    stock: 20,
  },
];

export const mockReels: VideoReel[] = [
  {
    id: 'reel1',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: '/placeholder-thumb.jpg',
    product: mockProducts[0],
    views: 125000,
    likes: 8500,
    comments: 342,
    uploadDate: '2024-12-15',
    duration: 30,
  },
  {
    id: 'reel2',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: '/placeholder-thumb.jpg',
    product: mockProducts[1],
    views: 89000,
    likes: 5200,
    comments: 198,
    uploadDate: '2024-12-14',
    duration: 25,
  },
  {
    id: 'reel3',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: '/placeholder-thumb.jpg',
    product: mockProducts[2],
    views: 156000,
    likes: 12300,
    comments: 567,
    uploadDate: '2024-12-16',
    duration: 15,
  },
];
